# 默认使用配置
spring:
  pid:
    file: log/mms-service.pid
  profiles:
    active: dev

  application:
    name: test-codeGenerate

  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 5000
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000

mybatis-plus:
  #xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-column-underline: true
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #JdbcTypeForNull
    jdbc-type-for-null: 'null'

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

---
server:
  port: 9999 #端口号


spring:
  profiles: dev

  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://172.23.0.199:3306/yzf_mms?useSSL=false&verifyServerCertificate=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8



